### Data preprocessing:

In [153]:
import pandas as pd

In [154]:
raw_data = pd.read_csv('Absenteeism-data.csv')

In [155]:
raw_data.head()

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

In [156]:
df = raw_data.copy()

In [157]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [158]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   ID                         700 non-null    int64  
 1   Reason for Absence         700 non-null    int64  
 2   Date                       700 non-null    object 
 3   Transportation Expense     700 non-null    int64  
 4   Distance to Work           700 non-null    int64  
 5   Age                        700 non-null    int64  
 6   Daily Work Load Average    700 non-null    float64
 7   Body Mass Index            700 non-null    int64  
 8   Education                  700 non-null    int64  
 9   Children                   700 non-null    int64  
 10  Pets                       700 non-null    int64  
 11  Absenteeism Time in Hours  700 non-null    int64  
dtypes: float64(1), int64(10), object(1)
memory usage: 65.8+ KB


### Drop 'ID':

In [160]:
df = df.drop(['ID'], axis = 1)

In [161]:
df.head()

Reason for Absence        Date  Transportation Expense  Distance to Work  \
0                  26  07/07/2015                     289                36   
1                   0  14/07/2015                     118                13   
2                  23  15/07/2015                     179                51   
3                   7  16/07/2015                     279                 5   
4                  23  23/07/2015                     289                36   

   Age  Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0   33                  239.554               30          1         2     1   
1   50                  239.554               31          1         1     0   
2   38                  239.554               31          1         0     0   
3   39                  239.554               24          1         2     0   
4   33                  239.554               30          1         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

### 'Reason for Absence':

In [163]:
df['Reason for Absence'].min()

0

In [164]:
df['Reason for Absence'].max()

28

In [165]:
pd.unique(df['Reason for Absence'])

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16], dtype=int64)

In [166]:
len(df['Reason for Absence'].unique())

28

In [167]:
sorted(df['Reason for Absence'].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28]

In [168]:
reasons_columns = pd.get_dummies(df['Reason for Absence'])

In [169]:
#reasons_columns

In [170]:
reasons_columns['check'] = reasons_columns.sum(axis=1)
reasons_columns['check'].sum()

700

In [171]:
reasons_columns['check'].unique()

array([1], dtype=int64)

In [172]:
reasons_columns = reasons_columns.drop(['check'], axis = 1)

In [173]:
reasons_columns = pd.get_dummies(df['Reason for Absence'], drop_first=True, dtype=int)

In [174]:
#reasons_columns

**Group the reasons for absence:**

In [176]:
df.columns.values

array(['Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours'], dtype=object)

In [177]:
reasons_columns.columns.values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 21, 22, 23, 24, 25, 26, 27, 28], dtype=int64)

In [178]:
df = df.drop(['Reason for Absence'], axis=1)

In [179]:
df.head()

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

In [180]:
reason_1 = reasons_columns.loc[:, 1:14].max(axis=1)
reason_2 = reasons_columns.loc[:, 15:17].max(axis=1)
reason_3 = reasons_columns.loc[:, 18:21].max(axis=1)
reason_4 = reasons_columns.loc[:, 22:].max(axis=1)

In [181]:
#reason_2.sum()

**Concatenate and reorder columns:**

In [183]:
df = pd.concat([df, reason_1, reason_2, reason_3, reason_4], axis=1)

In [184]:
df.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 0, 1, 2, 3],
      dtype=object)

In [185]:
column_names = ['Date', 'Transportation Expense', 'Distance to Work', 'Age', 'Daily Work Load Average',
                'Body Mass Index', 'Education', 'Children', 'Pets', 'Absenteeism Time in Hours',
                'Reason_1', 'Reason_2', 'Reason_3', 'Reason_4']

In [186]:
df.columns = column_names

In [187]:
df.head()

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  Reason_1  Reason_2  Reason_3  Reason_4  
0                          4         0         0         0         1  
1                          0         0         0         0         0  
2                          2         0         0         0         1  
3                          4         1         0         0         0  
4                          2         0         0         0         1

In [188]:
column_names_reordered = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Date', 'Transportation Expense', 'Distance to Work', 'Age', 'Daily Work Load Average',
                'Body Mass Index', 'Education', 'Children', 'Pets', 'Absenteeism Time in Hours']

In [189]:
df = df[column_names_reordered]

In [190]:
df.head()

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  07/07/2015                     289   
1         0         0         0         0  14/07/2015                     118   
2         0         0         0         1  15/07/2015                     179   
3         1         0         0         0  16/07/2015                     279   
4         0         0         0         1  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

In [191]:
df_reason_mod = df.copy()

**Date column transformation:**

In [193]:
type(df_reason_mod['Date'][0])

str

In [194]:
df_reason_mod['Date'] = pd.to_datetime(df_reason_mod['Date'], format='%d/%m/%Y')

In [195]:
df_reason_mod['Date'].head()

0   2015-07-07
1   2015-07-14
2   2015-07-15
3   2015-07-16
4   2015-07-23
Name: Date, dtype: datetime64[ns]

In [196]:
df_reason_mod['Date'][0]

Timestamp('2015-07-07 00:00:00')

In [197]:
list_months = []

In [198]:
df_reason_mod.shape

(700, 14)

In [199]:
for i in range(df_reason_mod.shape[0]):
    list_months.append(df_reason_mod['Date'][i].month)

In [200]:
#list_months
len(list_months)

700

In [201]:
df_reason_mod['Month Value'] = list_months

In [202]:
#df_reason_mod.head()

In [203]:
df_reason_mod['Date'][699].weekday()

3

In [204]:
def date_to_weekday(data_value):
    return data_value.weekday()

In [205]:
df_reason_mod['Day of the Week'] = df_reason_mod['Date'].apply(date_to_weekday)

In [206]:
#df_reason_mod.head()

In [207]:
df_reason_mod = df_reason_mod.drop(['Date'], axis=1)
#df_reason_mod.head()

In [208]:
df_reason_mod.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Month Value',
       'Day of the Week'], dtype=object)

In [209]:
column_names_upd = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
                    'Month Value','Day of the Week', 'Transportation Expense',
                    'Distance to Work', 'Age', 'Daily Work Load Average', 'Body Mass Index',
                    'Education', 'Children', 'Pets', 'Absenteeism Time in Hours']

In [210]:
df_reason_mod = df_reason_mod[column_names_upd]
#df_reason_mod.head()

In [211]:
df_reason_date_mod = df_reason_mod.copy()

In [212]:
type(df_reason_date_mod['Transportation Expense'][0])

numpy.int64

In [213]:
type(df_reason_date_mod['Distance to Work'][0])

numpy.int64

In [214]:
type(df_reason_date_mod['Age'][0])

numpy.int64

In [215]:
type(df_reason_date_mod['Daily Work Load Average'][0])

numpy.float64

In [216]:
type(df_reason_date_mod['Body Mass Index'][0])

numpy.int64

**Remaining columns: (Education, Children, Pets)**

In [218]:
df_reason_date_mod['Education'].unique()

array([1, 3, 2, 4], dtype=int64)

In [219]:
df_reason_date_mod['Education'].value_counts()

Education
1    583
3     73
2     40
4      4
Name: count, dtype: int64

In [220]:
df_reason_date_mod['Education'] = df_reason_date_mod['Education'].map({1:0, 2:1, 3:1, 4:1})

In [221]:
df_reason_date_mod['Education'].value_counts()

Education
0    583
1    117
Name: count, dtype: int64

In [293]:
df_preprocessed = df_reason_date_mod.copy()
df_preprocessed.head(10)

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   
5         0         0         0         1            7                4   
6         0         0         0         1            7                4   
7         0         0         0         1            7                4   
8         0         0         1         0            7                0   
9         0         0         0         1            7                0   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   
5                     179                51   38                  239.554   
6                     361                52   28                  239.554   
7                     260                50   36                  239.554   
8                     155                12   34                  239.554   
9                     235                11   37                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2  
5               31          0         0     0                          2  
6               27          0         1     4                          8  
7               23          0         4     0                          4  
8               25          0         2     0                         40  
9               29          1         1     1                          8

In [295]:
#df_preprocessed.isna().sum()

In [297]:
df_preprocessed.to_csv('AbsenteeismPreprocessed.csv', sep=',', index=False)